skip virtualenv check if already activated (#863)
This allows the user to choose their virtualenv method, e.g.
[Pipenv](https://docs.pipenv.org/).

diff --git a/algo b/algo
--- a/algo
+++ b/algo
@@ -2,13 +2,16 @@
 
 set -e
 
-ACTIVATE_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/env/bin/activate"
-if [ -f "$ACTIVATE_SCRIPT" ]
+if [ -z ${VIRTUAL_ENV+x} ]
 then
-	source $ACTIVATE_SCRIPT
-else
-	echo "$ACTIVATE_SCRIPT not found.  Did you follow documentation to install dependencies?"
-	exit 1
+	ACTIVATE_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/env/bin/activate"
+	if [ -f "$ACTIVATE_SCRIPT" ]
+	then
+		source $ACTIVATE_SCRIPT
+	else
+		echo "$ACTIVATE_SCRIPT not found.  Did you follow documentation to install dependencies?"
+		exit 1
+	fi
 fi
 
 SKIP_TAGS="_null encrypted"
